services:
  - type: web
    name: mern-ecommerce
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm --prefix backend run dev
    envVars:
      - key: MONGO_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: RAZORPAY_KEY_ID
        scope: build
      - key: RAZORPAY_KEY_SECRET
        scope: build
      - key: PORT
        value: 5000
